name: Build Docker Image

on:
  workflow_run:
    workflows: [Run Tests]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: docker build -t financial_app:latest .
